export const GRID_WIDTH = 80;
export const GRID_HEIGHT = 80;

export const SIM = {
  // Water
  BASE_WATER_RECHARGE: 0.4,
  MAX_WATER: 10.0,
  WATER_ABSORPTION_PER_ROOT: 0.4,
  TRANSPIRATION_PER_LEAF: 0.55,
  ROOT_COMPETITION_RATE: 0.06,

  // Nutrients
  MAX_NUTRIENTS: 10.0,
  NUTRIENT_GROWTH_BONUS: 0.20,
  NUTRIENT_ROOT_ACCESS_MIN: 0.3,
  NUTRIENT_DECAY: 0.02,

  // Light
  BASE_LIGHT: 1.0,
  SHADOW_REDUCTION: 0.25,
  SHADOW_HEIGHT_SCALE: 3.0,
  MIN_LIGHT: 0.1,

  // Energy / Photosynthesis
  PHOTOSYNTHESIS_RATE: 0.5,
  LEAF_EFFICIENCY_EXPONENT: 0.7,
  HEIGHT_LIGHT_BONUS: 0.7,
  MAINTENANCE_BASE: 0.05,
  MAINTENANCE_PER_HEIGHT: 0.03,
  MAINTENANCE_PER_ROOT: 0.03,
  MAINTENANCE_PER_LEAF: 0.04,

  // Growth
  MAX_HEIGHT: 10.0,
  MAX_ROOT_DEPTH: 10.0,
  MAX_LEAF_AREA: 8.0,
  GROWTH_EFFICIENCY: 0.3,

  // Reproduction
  SEED_ENERGY_COST: 0.8,
  SEED_RANGE_MIN: 1,
  SEED_RANGE_MAX: 3,
  SEED_RANGE_HEIGHT_DIVISOR: 2,
  SEED_INITIAL_ENERGY: 2.0,
  MUTATION_RATE: 0.1,
  CROSSOVER_MATE_RADIUS: 4,

  // Death / Decomposition
  STARVATION_THRESHOLD: 0,
  DECOMP_WATER_BOOST: 2.0,
  DECOMP_NUTRIENT_BOOST: 1.5,
  DECOMP_NUTRIENT_PER_HEIGHT: 0.3,

  // Age
  MAX_AGE: 500,

  // Disease / Blight
  DISEASE_DISTANCE_THRESHOLD: 0.25,
  DISEASE_DRAIN_PER_TICK: 0.15,
  DISEASE_PHOTO_PENALTY: 0.7,
  DISEASE_SPREAD_BASE: 0.30,
  DISEASE_CELL_DURATION_MIN: 15,
  DISEASE_CELL_DURATION_MAX: 25,
  DISEASE_EVENT_DURATION_MIN: 40,
  DISEASE_EVENT_DURATION_MAX: 80,
  DISEASE_SPAWN_CHANCE: 0.003,
  DISEASE_MIN_UNIFORMITY: 0.5,
  DISEASE_SCAN_RADIUS: 5,
  DISEASE_SCAR_DURATION: 40,
  DISEASE_SPAWN_MIN_TICK: 300,

  // Drought
  DROUGHT_EVAPORATION_RATE: 0.3,

  // Terrain
  RIVER_WATER_RECHARGE: 1.2,
  ROCK_WATER_RECHARGE: 0.08,
  ROCK_NUTRIENT_MAX: 0.5,
  HILL_LIGHT_BONUS: 0.35,
  HILL_WATER_PENALTY: 0.4,
  HILL_NUTRIENT_MAX: 3.0,
  HILL_ROOT_NUTRIENT_BONUS: 0.15,
  HILL_ROOT_NUTRIENT_THRESHOLD: 0.3,
  RIVER_SEEPAGE: 0.4,
  RIVER_NUTRIENT_SEEPAGE: 0.1,
  RIVER_NUTRIENT_BONUS: 2.0,

  // Wetland terrain
  WETLAND_WATER_RECHARGE: 0.7,
  WETLAND_NUTRIENT_BONUS: 2.0,
  WETLAND_NUTRIENT_MAX: 8.0,
  WETLAND_LIGHT_PENALTY: 0.25,
  WETLAND_HEIGHT_BONUS_MULT: 1.5,

  // Arid terrain
  ARID_WATER_RECHARGE: 0.12,
  ARID_NUTRIENT_MAX: 1.5,
  ARID_LIGHT_BONUS: 0.2,
  ARID_AQUIFER_ROOT_THRESHOLD: 0.4,
  ARID_AQUIFER_WATER_BONUS: 0.6,

  // Terrain maintenance multipliers (per-trait, Soil = 1.0 implicit)
  HILL_MAINT_ROOT_MULT: 3.0,     // rock is hard to dig
  HILL_MAINT_HEIGHT_MULT: 1.5,   // wind stress on tall plants
  HILL_MAINT_LEAF_MULT: 1.0,

  WETLAND_MAINT_ROOT_MULT: 2.5,  // anoxic deep soil
  WETLAND_MAINT_HEIGHT_MULT: 1.0,
  WETLAND_MAINT_LEAF_MULT: 0.85, // humidity protects leaves

  ARID_MAINT_ROOT_MULT: 0.8,     // easy dig in sand
  ARID_MAINT_HEIGHT_MULT: 1.2,   // heat stress
  ARID_MAINT_LEAF_MULT: 3.0,     // transpiration water loss

  // Terrain seed fitness weights (additive on normalized genome fracs, Soil = 0 implicit)
  HILL_SEED_ROOT_WEIGHT: -0.3,
  HILL_SEED_HEIGHT_WEIGHT: -0.2,
  HILL_SEED_LEAF_WEIGHT: 0.15,

  WETLAND_SEED_ROOT_WEIGHT: -0.25,
  WETLAND_SEED_HEIGHT_WEIGHT: 0.1,
  WETLAND_SEED_LEAF_WEIGHT: 0.2,

  ARID_SEED_ROOT_WEIGHT: 0.3,
  ARID_SEED_HEIGHT_WEIGHT: -0.15,
  ARID_SEED_LEAF_WEIGHT: -0.3,

  // Allelopathy
  ALLELOPATHY_DAMAGE_RATE: 0.15,
  ALLELOPATHY_MAINTENANCE_RATE: 0.06,

  // Defense
  DEFENSE_GRAZE_REDUCTION: 0.7,
  DEFENSE_HERBIVORE_DAMAGE: 0.3,
  DEFENSE_MAINTENANCE_RATE: 0.05,
} as const;

export const GRASS = {
  MAX_HEIGHT: 2.0,
  MAX_ROOT_DEPTH: 3.0,
  MAX_LEAF_AREA: 4.0,

  MAINTENANCE_BASE: 0.02,
  MAINTENANCE_PER_HEIGHT: 0.02,
  MAINTENANCE_PER_ROOT: 0.02,
  MAINTENANCE_PER_LEAF: 0.03,

  SEED_ENERGY_COST: 0.4,
  SEED_RANGE_MAX: 4,
  SEED_RANGE_HEIGHT_DIVISOR: 4,
  SEED_INITIAL_ENERGY: 1.5,
  GROWTH_EFFICIENCY: 0.5,

  MAX_AGE: 200,
  SHADOW_REDUCTION: 0.05,
  SHADOW_HEIGHT_SCALE: 1.0,
  HEIGHT_LIGHT_BONUS: 0.1,

  DECOMP_WATER_BOOST: 1.0,
  DECOMP_NUTRIENT_BOOST: 0.8,
  DECOMP_NUTRIENT_PER_HEIGHT: 0.1,

  SEEDLING_HEIGHT: 0.3,
  SEEDLING_ROOT: 0.3,
  SEEDLING_LEAF: 0.5,
} as const;

export const INITIAL_GRASS_FRACTION = 0.4;
